use_frameworks!

platform :ios, '8.0'

target 'LTNetRequestManager_Example' do
  pod 'LTNetRequestManager', :path => '../'

  target 'LTNetRequestManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
